### ISSUE TITLE
Some questions about the ESXI dashboard

### ISSUE THREAD

**Issue by smaat1980** [EvisHome/home-assistant#4]
Hello Jukka,

First of all, I would like to thank you for sharing your cool dashboard.

I have the following small problems and I hope you know what they could be.

- At VM's I have borders around the buttons snapshot etc. See screenshot borders.

- The other problem I have is that I see few entities and not everything you have in your dashboard. I'm probably doing something wrong, but I don't know what. See screenshot entities. There are plenty of attributes you can choose that are all similar. As a result, I miss quite a bit in the dashboard or are not displayed.

thanks in advance for your help

Greeting,

Stefan

First 
![screenshot dashboard](https://github.com/EvisHome/Home-Assistant/assets/129669257/657c9b14-3bec-407f-97ec-1eea6d20dd0a)
![Borders](https://github.com/EvisHome/Home-Assistant/assets/129669257/a4b28344-93c8-437e-8e0e-a5307246149c)
![entities](https://github.com/EvisHome/Home-Assistant/assets/129669257/398b2ff3-af51-4aee-9abe-1de0eb538dd7)

**Comment by EvisHome** [comment]
Hi,

there has probably been some (breaking) changes to some of the stuff used in this dashboard. You could try to create sensors from the attributes. If I recall I had done something like that .. sorry but I can't really help much here, I Haven't updated this, since I stopped using ESXi myself a while back, transferred fully to Proxmox, but haven't really made a proper dashboard for that one yet.
